name: Run Data Fetch and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This schedule runs the workflow every hour; adjust as needed.

jobs:
  run-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetching script
        run: |
          python fetch_data.py

      - name: Zip CSV files
        run: |
          echo "[DEBUG] Creating zip archive for all CSV files..."
          zip -r final_csvs.zip *.csv
          ls -lh final_csvs.zip

      - name: Create GitHub Release and Upload Zip
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          body: "Automated release generated by GitHub Actions"
          draft: false
          prerelease: false
          files: final_csvs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
